// angular-frontend/src/app/shared/map-picker.ts
import { AfterViewInit, Component, ElementRef, input, output, viewChild } from '@angular/core';
import * as L from 'leaflet';

@Component({
  selector: 'app-map-picker',
  template: `<div class="overflow-hidden rounded-md border" style="height: 250px;" #mapEl></div>`,
})
export class MapPickerComponent implements AfterViewInit {
  readonly lat = input<number | null>(null);
  readonly lng = input<number | null>(null);
  readonly latLngChange = output<{ lat: number; lng: number }>();

  readonly mapEl = viewChild<ElementRef<HTMLDivElement>>('mapEl');

  private map: L.Map | null = null;
  private marker: L.Marker | null = null;

  ngAfterViewInit(): void {
    const el = this.mapEl()?.nativeElement;
    if (!el) return;
    const hasPos = typeof this.lat() === 'number' && typeof this.lng() === 'number';
    const center: L.LatLngExpression = hasPos ? [this.lat() as number, this.lng() as number] : [28.0339, 1.6596];
    const zoom = hasPos ? 10 : 5;
    this.map = L.map(el).setView(center, zoom);
    L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
      attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a>',
    }).addTo(this.map);

    this.map.on('click', (e: L.LeafletMouseEvent) => {
      this.latLngChange.emit({ lat: e.latlng.lat, lng: e.latlng.lng });
      this.updateMarker(e.latlng.lat, e.latlng.lng);
    });

    if (hasPos) this.updateMarker(this.lat() as number, this.lng() as number);
  }

  private updateMarker(lat: number, lng: number): void {
    if (!this.map) return;
    if (!this.marker) {
      this.marker = L.marker([lat, lng], { draggable: true }).addTo(this.map);
      this.marker.on('dragend', () => {
        const pos = this.marker!.getLatLng();
        this.latLngChange.emit({ lat: pos.lat, lng: pos.lng });
      });
    } else {
      this.marker.setLatLng([lat, lng]);
    }
    this.map.setView([lat, lng], this.map.getZoom());
  }
}

// frontend/src/components/app/map-picker.tsx
import { useEffect } from 'react'
import { MapContainer, Marker, TileLayer, useMap, useMapEvents } from 'react-leaflet'
import L from 'leaflet'

type LatLng = { lat: number; lng: number }

function ClickHandler({ onChange }: { onChange: (lat: number, lng: number) => void }) {
  useMapEvents({
    click(e) {
      onChange(e.latlng.lat, e.latlng.lng)
    },
  })
  return null
}

function Recenter({ lat, lng }: LatLng) {
  const map = useMap()
  useEffect(() => {
    map.setView([lat, lng], map.getZoom())
  }, [lat, lng, map])
  return null
}

export function MapPicker({
  lat,
  lng,
  onChange,
  height = 250,
}: {
  lat?: number | null
  lng?: number | null
  onChange: (lat: number, lng: number) => void
  height?: number
}) {
  const hasPos = typeof lat === 'number' && typeof lng === 'number' && !Number.isNaN(lat) && !Number.isNaN(lng)
  const center: [number, number] = hasPos ? [lat as number, lng as number] : [28.0339, 1.6596]
  const zoom = hasPos ? 10 : 5

  return (
    <div style={{ height }} className="overflow-hidden rounded-md border">
      <MapContainer center={center} zoom={zoom} style={{ height: '100%', width: '100%' }} scrollWheelZoom={false}>
        <TileLayer
          attribution='&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a>'
          url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
        />
        <ClickHandler onChange={onChange} />
        {hasPos && <Recenter lat={lat as number} lng={lng as number} />}
        {hasPos && (
          <Marker
            position={[lat as number, lng as number]}
            draggable
            eventHandlers={{
              dragend: (e) => {
                const m = e.target as L.Marker
                const pos = m.getLatLng()
                onChange(pos.lat, pos.lng)
              },
            }}
          />
        )}
      </MapContainer>
    </div>
  )
}
