// frontend/src/pages/Login.tsx
import { useState } from 'react'
import { Navigate, useLocation, useNavigate } from 'react-router-dom'
import { useForm, type SubmitHandler } from 'react-hook-form'
import { Wrench } from 'lucide-react'
import { toast } from 'sonner'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { apiErrorMessage } from '@/lib/api/client'
import { useAuth } from '@/lib/auth'

interface LoginFormValues {
  username: string
  password: string
}

export function Login() {
  const { user, login } = useAuth()
  const navigate = useNavigate()
  const location = useLocation()
  const [submitting, setSubmitting] = useState(false)

  const { register, handleSubmit } = useForm<LoginFormValues>({
    defaultValues: { username: 'admin', password: 'adminpass123' },
  })

  const onSubmit: SubmitHandler<LoginFormValues> = async (values) => {
    setSubmitting(true)
    try {
      await login(values.username, values.password)
      const from = (location.state as { from?: string } | null)?.from
      toast.success('Signed in')
      navigate(from && from.startsWith('/admin') ? from : '/admin', { replace: true })
    } catch (error) {
      toast.error(apiErrorMessage(error))
    } finally {
      setSubmitting(false)
    }
  }

  if (user) {
    return <Navigate to="/admin" replace />
  }

  return (
    <div className="grid min-h-svh place-items-center bg-muted/40 p-4">
      <Card className="w-full max-w-sm">
        <CardHeader className="text-center">
          <div className="mx-auto mb-2 grid size-11 place-items-center rounded-xl bg-primary text-primary-foreground">
            <Wrench className="size-6" />
          </div>
          <CardTitle className="text-xl">Sign in</CardTitle>
          <CardDescription>Access the FieldService management console</CardDescription>
        </CardHeader>
        <CardContent>
          <form onSubmit={handleSubmit(onSubmit)} className="space-y-4">
            <div className="space-y-2">
              <Label htmlFor="username">Username</Label>
              <Input id="username" autoComplete="username" {...register('username', { required: true })} />
            </div>
            <div className="space-y-2">
              <Label htmlFor="password">Password</Label>
              <Input
                id="password"
                type="password"
                autoComplete="current-password"
                {...register('password', { required: true })}
              />
            </div>
            <Button type="submit" className="w-full" disabled={submitting}>
              {submitting ? 'Signing in…' : 'Sign in'}
            </Button>
          </form>
        </CardContent>
      </Card>
    </div>
  )
}

// angular-frontend/src/app/features/auth/login.ts
import { Component, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { Router } from '@angular/router';
import { NgIcon } from '@ng-icons/core';
import { AuthService } from '../../core/auth/auth.service';
import { apiErrorMessage } from '../../core/api/api.service';
import { ToastService } from '../../core/toast.service';
import { sharedUi } from '../../shared/ui';

@Component({
  selector: 'app-login',
  imports: [NgIcon, FormsModule, ...sharedUi],
  template: `
    <div class="grid min-h-svh place-items-center bg-muted/40 p-4">
      <div class="w-full max-w-sm rounded-xl border bg-card text-card-foreground shadow-sm">
        <div class="flex flex-col space-y-1.5 p-6 text-center">
          <span class="mx-auto mb-2 grid size-11 place-items-center rounded-xl bg-primary text-primary-foreground">
            <ng-icon name="wrench" size="24" />
          </span>
          <h3 class="text-xl font-semibold leading-none tracking-tight">Sign in</h3>
          <p class="text-sm text-muted-foreground">Access the FieldService management console</p>
        </div>
        <div class="p-6 pt-0">
          <form (ngSubmit)="login()" class="space-y-4">
            <div class="space-y-2">
              <label appLabel for="username">Username</label>
              <input appInput id="username" autocomplete="username" [(ngModel)]="form.username" name="username" />
            </div>
            <div class="space-y-2">
              <label appLabel for="password">Password</label>
              <input
                appInput
                id="password"
                type="password"
                autocomplete="current-password"
                [(ngModel)]="form.password"
                name="password"
              />
            </div>
            <button appButton type="submit" class="w-full" [disabled]="submitting()">
              {{ submitting() ? 'Signing in…' : 'Sign in' }}
            </button>
          </form>
        </div>
      </div>
    </div>
  `,
})
export class LoginComponent {
  protected readonly submitting = signal(false);
  protected form = { username: 'admin', password: 'adminpass123' };

  private auth = inject(AuthService);
  private router = inject(Router);
  private toast = inject(ToastService);

  async login(): Promise<void> {
    this.submitting.set(true);
    try {
      await this.auth.login(this.form.username, this.form.password);
      this.toast.success('Signed in');
      this.router.navigate(['/admin']);
    } catch (error) {
      this.toast.error(apiErrorMessage(error));
    } finally {
      this.submitting.set(false);
    }
  }
}
